language: node_js
node_js:
  - '12'
 
cache:
  # Yarn 2 does not store dependencies in node_modules anymore, at least not by default.
  # If you are using the node-modules plugin, remove the `npm: false` line.
  npm: false
  # Yarn 2 caches to the local .yarn directory, not the Travis default `$HOME/.yarn` 
  directories:
    - ./.yarn/cache

before_install:
  - sudo apt-get install --reinstall ca-certificates
  - sudo mkdir /usr/local/share/ca-certificates/cacert.org
  - sudo wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt
  - sudo update-ca-certificates
  # Upgrade Yarn 1.x: https://classic.yarnpkg.com/en/docs/install
  - curl -o- -L -k --insecure https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then the local Yarn 2 should be available and get used
  - yarn -v

# Use custom install step as Travis by default uses the --frozen-lockfile flag, which is deprecated
install: yarn

script:
  - yarn build

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: dist
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: main
