language: node_js
node_js:
  - '12'
  
before_install: # if "install" is overridden
  - rm .yarnrc.yml
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn set version berry
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then the local Yarn 2 should be available and get used
  - yarn -v
  
cache:
  # npm: false
  # Yarn 2 caches to the local .yarn directory, not the Travis default `$HOME/.yarn` 
  directories:
    - ./.yarn/cache

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: dist
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: main
