language: node_js
node_js:
  - '12'
 
cache:
  # Yarn 2 does not store dependencies in node_modules anymore, at least not by default.
  # If you are using the node-modules plugin, remove the `npm: false` line.
  # Yarn 2 caches to the local .yarn directory, not the Travis default `$HOME/.yarn` 
  directories:
    - ./.yarn/cache

before_install:
  - npm install -g yarn
  - yarn set version berry

# Use custom install step as Travis by default uses the --frozen-lockfile flag, which is deprecated
install: yarn

script:
  - yarn build

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: dist
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages)
  target_branch: gh-pages
  on:
    # Which branch on commit/push will trigger deployment
    branch: main
